name: gluon_vision_docs
dependencies:
- python
- sphinx>=1.5.5
- scipy
- numpy
- matplotlib
- sphinx_rtd_theme
- pip:
  - https://github.com/mli/mx-theme/tarball/0.3.1
  - sphinx-gallery
  - mxnet-cu92mkl==1.6.0b20190808
  # - guzzle_sphinx_theme
  - recommonmark
  - Image
  - awscli
  - tqdm
  - requests
  - Pillow
  - opencv-python
